spring:
  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    password:
    username: sa
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
