server:
  port: 30080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://192.168.64.2:30432/processflow
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
